editing from dev...

updating again from dev...

updating from development...

development

This line writing from master...

master
This line editing from the master branch...

This file contails string related java code...
This code is updated from the GIT GUI...
